export const dummyShipData = [{
    "name": "VENUS-103",
    "remaining_fuel": 25,
    "capacity": 12,
    "top_speed": 300,
    "condition": 0.75,
    "crew_needed": 2,
  },
  {
    "name": "MERCURY-1480",
    "remaining_fuel": 25,
    "capacity": 20,
    "top_speed": 500,
    "condition": 1,
    "crew_needed": 2,
  },
  {
    "name": "SATURN-1329",
    "remaining_fuel": 25,
    "capacity": 47,
    "top_speed": 270,
    "condition": 0.74,
    "crew_needed": 3,
  },
  {
    "name": "LUNAR-672",
    "remaining_fuel": 25,
    "capacity": 3,
    "top_speed": 605,
    "condition": 0.73,
    "crew_needed": 2,
  },
  {
    "name": "THUNDERBIRD-0",
    "remaining_fuel": 25,
    "capacity": 4,
    "top_speed": 505,
    "condition": 0.43,
    "crew_needed": 5,
  },
  {
    "name": "NEPTUNE-593",
    "remaining_fuel": 25,
    "capacity": 4,
    "top_speed": 505,
    "condition": 0.43,
    "crew_needed": 5,
  },
  {
    "name": "PLUTO-298",
    "remaining_fuel": 25,
    "capacity": 4,
    "top_speed": 505,
    "condition": 0.43,
    "crew_needed": 5,
  },
  {
    "name": "JUPITER-1181",
    "remaining_fuel": 25,
    "capacity": 100,
    "top_speed": 90,
    "condition": 1,
    "crew_needed": 12,
  }]